service: outil

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ${self:custom.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: 'arn:aws:s3:::${self:custom.inputBucket}/*'
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
          Resource: 'arn:aws:s3:::${self:custom.outputBucket}/*'
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: 'arn:aws:s3:::${self:custom.inputBucket}'
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: 'arn:aws:s3:::${self:custom.outputBucket}'
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: ${self:custom.deleteObjectsFromS3Queue.arn}
  environment:
    INPUT_BUCKET: ${self:custom.inputBucket}
    OUTPUT_BUCKET: ${self:custom.outputBucket}
    DELETE_OBJECTS_FROM_S3_QUEUE_URL: ${self:custom.deleteObjectsFromS3Queue.url}

functions:
  main:
    handler: src/lambda-main.handler
    events:
      - http:
          method: any
          path: /{any+}
    layers:
      - !Sub arn:aws:lambda:${self:custom.region}:${AWS::AccountId}:layer:ffmpeg:1
  listStorage:
    handler: src/lambda-list-storage.handler
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    S3InputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.inputBucket}
    S3OutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.outputBucket}
    DeleteObjectsFromS3Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.deleteObjectsFromS3Queue.name}

custom:
  region: ca-central-1
  inputBucket: ${file(env.yml):INPUT_BUCKET}-${opt:stage, 'dev'}
  outputBucket: ${file(env.yml):OUTPUT_BUCKET}-${opt:stage, 'dev'}
  deleteObjectsFromS3Queue:
    name: ${file(env.yml):DELETE_OBJECTS_FROM_S3_QUEUE}-${opt:stage, 'dev'}
    arn: !GetAtt DeleteObjectsFromS3Queue.Arn
    url: !Ref DeleteObjectsFromS3Queue
